#!/bin/bash

AUTH_KEY_LEN=36

if [ ${#ALAKAZAM_KEY} -ne $AUTH_KEY_LEN ] || [ ${#GENGAR_KEY} -ne $AUTH_KEY_LEN ]; then
    echo "Invalid authentication key - Expected $AUTH_KEY_LEN characters."
    exit 1
fi
